USE [master]
GO

/****** Object:  Database [UsilForLiveDB]    Script Date: 19/06/2017 18:21:35 ******/
CREATE DATABASE [UsilForLiveDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UsilForLiveDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\UsilForLiveDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'UsilForLiveDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\UsilForLiveDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [UsilForLiveDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UsilForLiveDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UsilForLiveDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UsilForLiveDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UsilForLiveDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UsilForLiveDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UsilForLiveDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UsilForLiveDB] SET  MULTI_USER 
GO

ALTER DATABASE [UsilForLiveDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UsilForLiveDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UsilForLiveDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UsilForLiveDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [UsilForLiveDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UsilForLiveDB] SET  READ_WRITE 
GO


alter table AsesoriaV
ADD CONSTRAINT FK_ASESORIA_CURSO FOREIGN KEY(IdCurso_Detalle) references Curso_Detalle(IdCurso_Detalle)
GO
alter table AsesoriaV
ADD CONSTRAINT FK_ASESORIA_PROFESOR FOREIGN KEY(IdProfesor) references Profesor(IdProfesor)
GO
alter table Alumno
ADD CONSTRAINT FK_ALUMNO_ASESORIA FOREIGN KEY(IdAsesoria) references AsesoriaV(IdAsesoria)
GO